import { Router } from 'express';
import authRoutes from './authRoutes';
import userRoutes from './userRoutes';
import providerRoutes from './providerRoutes';
import eventRequestRoutes from './eventRequestRoutes';
import quoteRoutes from './quoteRoutes';
import bookingRoutes from './bookingRoutes';
import portfolioRoutes from './portfolioRoutes';
import reviewRoutes from './reviewRoutes';
import adminRoutes from './adminRoutes';
import verificationRoutes from './verificationRoutes';
import notificationRoutes from './notificationRoutes';
import pdfImportRoutes from './pdfImportRoutes';
import jessRoutes from './jessRoutes';
import favoriteRoutes from './favoriteRoutes';
import packageRoutes, { addonRouter, availabilityRouter } from './packageRoutes';
import eventRoutes from './eventRoutes';
import uploadRoutes from './uploadRoutes';
import stripeRoutes from './stripeRoutes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/providers', providerRoutes);
router.use('/event-requests', eventRequestRoutes);
router.use('/quotes', quoteRoutes);
router.use('/bookings', bookingRoutes);
router.use('/portfolio', portfolioRoutes);
router.use('/reviews', reviewRoutes);
router.use('/admin', adminRoutes);
router.use('/verification', verificationRoutes);
router.use('/notifications', notificationRoutes);
router.use('/pdf-import', pdfImportRoutes);
router.use('/jess', jessRoutes);
router.use('/favorites', favoriteRoutes);
router.use('/packages', packageRoutes);
router.use('/addons', addonRouter);
router.use('/availability', availabilityRouter);
router.use('/events', eventRoutes);
router.use('/upload', uploadRoutes);
router.use('/stripe', stripeRoutes);

export default router;
