-- Add new ProviderType enum values if they don't exist
ALTER TYPE "ProviderType" ADD VALUE IF NOT EXISTS 'RESTO_VENUE';
ALTER TYPE "ProviderType" ADD VALUE IF NOT EXISTS 'CATERER';
ALTER TYPE "ProviderType" ADD VALUE IF NOT EXISTS 'ENTERTAINMENT';
ALTER TYPE "ProviderType" ADD VALUE IF NOT EXISTS 'PHOTO_VIDEO';
ALTER TYPE "ProviderType" ADD VALUE IF NOT EXISTS 'FLORIST_DECOR';
